#!/bin/bash

# 步骤1: 使用adb pull指定文件到当前目录
echo "---------------拉取资源到本地---------------"
adb pull /sdcard/Android/data/com.xiaopeng.speech.resourcecenter/files/databases/test/ .

# 步骤2: 切换到指定路径的仓库，并提交更改,替换成自己仓库的路径
echo "---------------拷贝资源到仓库---------------"
cp -f test/resource_coordinates_info.json /Users/wanghx2/Develop/au8155_xp/f30/carspeech/assets/ngc/
cp -f test/resource.db /Users/wanghx2/Develop/au8155_xp/f30/carspeech/assets/ngc/
cd /Users/wanghx2/Develop/au8155_xp/

echo "---------------提交资源到指定分支---------------"
git add .
git commit -m "[ Modify      ] 更新ngc资源
[ Project     ] H93/F30
[ Module      ] ngc
[ Description ] 见需求描述
[ Reference   ] http://zendao.xiaopeng.local//zentao/bug-view-249216.html
[ Company     ] 北京小鹏
[ Team        ] 智能语音大屏开发组"
git pull
# 步骤3: 使用git review
# 获取当前仓库分支名称
current_branch=$(git symbolic-ref --short HEAD)
git review $current_branch